---
#
#  This demostrates using kitchen-verifier-serverspec
#  Remotely directly on the server running serverspec in exec mode
#  you must have a spec_helper.rb
#    require 'serverspec'
#    set :backend, :exec
#
driver:
  name: ssh
  ssh_key: C:/repository/templates/test.pem
  username: centos
  sudo: true

provisioner:
  name: ansible_playbook
  hosts: tomcat-servers
  ansible_connection: local
  ansible_verbose: true
  ansible_verbosity: 4
  require_chef_for_busser: false

platforms:
  - name: centos-7.0

verifier:
  name: serverspec

suites:
  - name: ansible
    driver_config:
      hostname: localhost
      port: 5580
#      username: ubuntu
      ssh_key: C:/keys/my.pem
    verifier:
      patterns:
      - roles/tomcat/spec/tomcat_spec.rb


